var DealerID='';var _domain='honda-eparts.com.au';var gImage=null;var gCanvas=null;var gContext=null;var canvasMinX=0,canvasMinY=0;var _offsetX=0,_offsetY=0,_mouseX,_mouseY,_mouseDownX,_mouseDownY,_mouseMoveX,_mouseMoveY;var _imagePosX,_imagePosY;var _scalefactor=2;var _scalefactor_zoomin=2;var _scalefactor_zoomout=2;var _hitTolerance=50;var zoom,zoomIn,zoomOut,mousePosX,mousePosY,paint;var _canvasWidth=390;var _canvasHeight=565; /*Added By Manikandan KP to configure GST percentage amount for Honda*/ var gstPercentageAmountHonda='';
var _centreX=_canvasWidth/2;var _centreY=_canvasHeight/2;var _hotspots=Array();$(document).ready(function(){init();init_mouse();});function init(){DealerID=$.cookies.get('accesskey[honda]'); gstPercentageAmountHonda=$.cookies.get('gstpercentageamount[honda]'); /*$('#TypeSelect option').remove();$('<option value="-1">Please select a Type</option>').appendTo('#TypeSelect');*/$('<option value="MB">Honda</option>').appendTo('#TypeSelect');$('#status').hide();if($.browser.msie&&!(document.documentMode>=9)){_scalefactor=1;$('#DiagramControls').hide();}
else{_scalefactor=2;}
$('#TypeSelect').change(function(){var selectedType=$(this).val();getYearshonda(selectedType);});var leftButtonDown=false;$("#imageCanvas").mousedown(function(e){if(e.which===1)leftButtonDown=true;});$("#imageCanvas").mouseup(function(e){if(e.which===1)leftButtonDown=false;});$('#imageCanvas').mousedown(function(e){_mouseDownX=mousePosX(e);_mouseDownY=mousePosY(e);_mouseMoveX=_mouseDownX;_mouseMoveY=_mouseDownY;_imagePosX=_mouseMoveX-_offsetX;_imagePosY=_mouseMoveY-_offsetY;$('#status').html('_mouseDownX:'+_mouseDownX+', _mouseDownY:'+_mouseDownY);});$('#imageCanvas').mouseover(function(e){$('#imageCanvas').css('cursor','move');}).mouseout(function(e){$('#imageCanvas').css('cursor','default');});function tweakMouseMoveEvent(e){if($.browser.msie&&!(document.documentMode>=9)&&!event.button){}
if(e.which===1&&!leftButtonDown)e.which=0;}
$('#imageCanvas').mousemove(function(e){tweakMouseMoveEvent(e);_mouseX=mousePosX(e);_mouseY=mousePosY(e);if(leftButtonDown){var newOffsetX=_offsetX+((_mouseX-_mouseMoveX)*_scalefactor);var newOffsetY=_offsetY+((_mouseY-_mouseMoveY)*_scalefactor);_mouseMoveX=_mouseX;_mouseMoveY=_mouseY;_offsetX=newOffsetX;_offsetY=newOffsetY;$('#status').html("'Left Mouse Down- _offsetX : "+newOffsetX+"_offsetY : "+newOffsetY);paint();}
else{_imagePosX=_mouseX*_scalefactor-_offsetX;_imagePosY=_mouseY*_scalefactor-_offsetY;$('#status').html(_mouseX+', '+_mouseY);var arLen=_hotspots.length;var gotone=false;for(var i=0,len=arLen;i<len;++i){if(((_hotspots[i].RefX>=_imagePosX-_hitTolerance)&&(_hotspots[i].RefX<=_imagePosX+_hitTolerance))&&((_hotspots[i].RefY>=_imagePosY-_hitTolerance)&&(_hotspots[i].RefY<=_imagePosY+_hitTolerance))){gotone=true;$('#imageCanvas').css('cursor','default');showInfoPopup(_hotspots[i]);highlightPartRow(_hotspots[i]);break;}}
if(gotone==false){$('#imageCanvas').css('cursor','move');hideInfoPopup();unhighlightPartRow();}}});$("tr.partrow").live('mouseover',function(){var partid=$(this).parent().attr("data-partid");var arrlen=_hotspots.length;for(var i=0;i<arrlen;i++){if(_hotspots[i].PartID==partid){break;}}
$(this).css('background-color','#fff');}).live('mouseout',function(){$(this).css('background-color','transparent');});$("#zoomIn").click(function(){zoomIn();});$("#zoomOut").click(function(){zoomOut();});gImage=new Image();if(document.getElementById('imageCanvas')!=null){gCanvas=document.getElementById('imageCanvas');gContext=gCanvas.getContext('2d');_canvasWidth=gCanvas.width;_canvasHeight=gCanvas.height;}
init_mouse();}
function init_mouse(){if($('#imageCanvas').offset()!=null){canvasMinX=$('#imageCanvas').offset().left;canvasMinY=$('#imageCanvas').offset().top;}
_centreX=_canvasWidth/2;_centreY=_canvasHeight/2;}
function mousePosX(event){var x=0;if(event.pageX||event.pageX===0){x=event.pageX-canvasMinX;}else if(event.offsetX||event.offsetX===0){x=event.offsetX;}
return x;};function mousePosY(event){var y=0;if(event.pageY||event.pagerY===0){y=event.pageY-canvasMinY;}else if(event.offsetY||event.offsetY===0){y=event.offsetY;}
return y;};function paint(){var newWidth=_canvasWidth*(1/_scalefactor);var newHeight=_canvasHeight*(1/_scalefactor);if(document.getElementById('imageCanvas')!=null)
gCanvas=document.getElementById('imageCanvas');gContext=gCanvas.getContext('2d');gContext.save();if(_scalefactor<=0){_scalefactor=0.5;gContext.scale(1/_scalefactor,1/_scalefactor);}
else{gContext.scale(1/_scalefactor,1/_scalefactor);}
gContext.fillStyle=gContext.strokeStyle="#fff";gContext.clearRect(0,0,_canvasWidth*_scalefactor,_canvasHeight*_scalefactor);gContext.drawImage(gImage,_offsetX,_offsetY);gContext.restore();}
function focusHotspot(Xpos,Ypos){var newOffsetX=Xpos-(_centreX*_scalefactor);var newOffsetY=Ypos-(_centreY*_scalefactor);_offsetX=-newOffsetX;_offsetY=-newOffsetY;$('#status').html("_offsetX : "+newOffsetX+"_offsetY : "+newOffsetY);paint();}
function showInfoPopup(partdata){var hotspotPosX=((partdata.RefX+_offsetX)*(1/_scalefactor))+canvasMinX;var hotspotPosY=((partdata.RefY+_offsetY)*(1/_scalefactor))+canvasMinY;$('#status').html('Got part '+partdata.RefNo);$('<div class="partinfopanel"></div>').html('<h4>'+partdata.PartNo+'</h4><p>'+partdata.Description+'</p>').appendTo('body').css('top',(hotspotPosY+20)+'px').css('left',(hotspotPosX+20)+'px').fadeIn('slow');}
function hideInfoPopup(){$('.partinfopanel').remove();}
function highlightPartRow(partdata){$('#part_'+partdata.PartID+' td').css('background-color','#7ce7fd');}
function unhighlightPartRow(){$('.partrow td').css('background-color','transparent');}
function zoomIn(){_scalefactor-=0.5;$('#status').html('Scale factor : '+_scalefactor);paint();}
function zoomOut(){_scalefactor+=0.5;$('#status').html('Scale factor : '+_scalefactor);paint();}
function setTypeSelector(selType){$('select#TypeSelect').children().attr('selected',function(i,selected){return $(this).val()==selType;});}
function getYearshonda(type,selectedYear){ 
if(DealerID==""){
DealerID=$.cookies.get('accesskey[honda]');
}
$.getJSON('http://'+_domain+'/Models/Years/'+type+'/'+DealerID+'?callback=?',function(data){$('#YearSelect option').remove();$('#YearSelect').change(function(){$('#ModelSelect option').remove();$('#AssemblySelect option').remove();$('#AccessorySelect option').remove();$('#AdrAssemblySelect option').remove();var selectedType=$('#TypeSelect').val();var thisYear=$(this).val();getModelsForYear(selectedType,thisYear);return false;});$('<option value="-1">Please select a Year</option>').appendTo('#YearSelect')
$.each(data,function(i,item){if(!item.match('~')){$('<option id="ModelYear_'+item+'">'+item+'</option>').attr('selected',item==selectedYear).appendTo('#YearSelect');}});});}
function getModelsForYear(type,year,selectedModelID){$.getJSON('http://'+_domain+'/Models/'+type+'/Year/'+year+'/'+DealerID+'?callback=?',function(data){$('#ModelSelect option').remove();$('#ModelSelect').change(function(){$('#AssemblySelect option').remove();$('#AccessorySelect option').remove();$('#AdrAssemblySelect option').remove();var modelId=$(this).children(":selected").attr("data-modelid");getModelImage(modelId);getAssembliesForModel(modelId);getAccessoriesForModel(modelId);getAdrAssembliesForModel(modelId);return false;});$('<option value="-1">Please select a Model</option>').appendTo('#ModelSelect');$.each(data,function(i,item){$('<option id="model_'+item.ModelID+'">'+item.MODEL+'</option>').attr('data-modelid',item.ModelID).attr('selected',item.ModelID==selectedModelID).appendTo('#ModelSelect');});});}
function getAssembliesForModel(modelId){$.getJSON('http://'+_domain+'/Assembly/Model/'+modelId+'/'+DealerID+'?callback=?',function(data){$('#AssemblySelect option').remove();$('#AssemblySelect').change(function(){$('#AccessorySelect').val(-1);$('#AdrAssemblySelect').val(-1);var assId=$(this).children(":selected").attr("data-assid");getAssemblyImage(assId);getPartsForAssembly(modelId,assId);return false;});$('<option value="-1">Please select an Assembly</option>').appendTo('#AssemblySelect')
$.each(data,function(i,item){$('<option id="assembly_'+item.AssemblyID+'">'+item.AddressNo+' - '+item.Name+'</option>').attr('data-assid',item.AssemblyID).appendTo('#AssemblySelect')});});}
function getAssembliesForModel2(modelId,selectedAssemblyID){$.getJSON('http://'+_domain+'/Assembly/Model/'+modelId+'/'+DealerID+'?callback=?',function(data){$('#AssemblySelect option').remove();$('#AssemblySelect').change(function(){$('#AccessorySelect').val(-1);$('#AdrAssemblySelect').val(-1);var assId=$(this).children(":selected").attr("data-assid");getAssemblyImage(assId);getPartsForAssembly(modelId,assId);return false;});$('<option value="-1">Please select an Assembly</option>').appendTo('#AssemblySelect')
$.each(data,function(i,item){$('<option id="assembly_'+item.AssemblyID+'">'+item.AddressNo+' - '+item.Name+'</option>').attr('data-assid',item.AssemblyID).attr('selected',item.AssemblyID==selectedAssemblyID).appendTo('#AssemblySelect')});});}
function getAccessoriesForModel(modelId){$.getJSON('http://'+_domain+'/Accessory/Model/'+modelId+'/'+DealerID+'?callback=?',function(data){$('#AccessorySelect option').remove();$('#AccessorySelect').change(function(){$('#AssemblySelect').val(-1);$('#AdrAssemblySelect').val(-1);var assId=$(this).children(":selected").attr("data-assid");getAssemblyImage(assId);getPartsForAssembly(modelId,assId);return false;});$('<option value="-1">Please select an Accessory</option>').appendTo('#AccessorySelect')
$.each(data,function(i,item){$('<option id="accessory_'+item.AssemblyID+'">'+item.AddressNo+' - '+item.Name+'</option>').attr('data-assid',item.AssemblyID).appendTo('#AccessorySelect')});});}
function getAdrAssembliesForModel(modelId){$.getJSON('http://'+_domain+'/AdrAssembly/Model/'+modelId+'/'+DealerID+'?callback=?',function(data){$('#AdrAssemblySelect option').remove();$('#AdrAssemblySelect').change(function(){$('#AssemblySelect').val(-1);$('#AccessorySelect').val(-1);var assId=$(this).children(":selected").attr("data-assid");getAssemblyImage(assId);getPartsForAssembly(modelId,assId);return false;});$('<option value="-1">Please select an Assembly</option>').appendTo('#AdrAssemblySelect')
$.each(data,function(i,item){$('<option id="adrassembly_'+item.AssemblyID+'">'+item.AddressNo+' - '+item.Name+'</option>').attr('data-assid',item.AssemblyID).appendTo('#AdrAssemblySelect')});});}
function getPartsForAssembly(modelId,assemblyId){$.getJSON('http://'+_domain+'/Part/Assembly/'+modelId+'/'+assemblyId+'/'+DealerID+'?callback=?',function(data){$('#PartsList tbody tr').remove();_hotspots.length=0;$.each(data,function(i,item){var partId=item.PartID;_hotspots.push(item);var PartNoCell;var itemPrice=0.00;var itemPartID="";if(item.SsPartNo!=null){PartNoCell="<td class=\"supersession\">"+item.SsPartNo+"</td>";itemPrice=item.SsPrice;itemPartID=item.SsPartNo;}
else{PartNoCell="<td>"+item.PartNo+"</td>";itemPrice=item.Price;itemPartID=item.PartNo;}
itemPrice=parseFloat(itemPrice);/*Updated By Manikandan KP to configure GST percentage amount for Honda*/ itemPrice=itemPrice+(itemPrice*gstPercentageAmountHonda);itemPrice=itemPrice.toFixed(2);if(parseFloat(itemPrice)>0){clm='<td><input type="button" id="btnAdd_'+item.PartID+'" class="productContentfooterLeft" value="Add to Cart_Farhan"></input></td>';}
else{var sel_year = document.getElementById('YearSelect').value; var sel_model = document.getElementById('ModelSelect').value; var sel_assembly = document.getElementById('AssemblySelect').value; clm='<td><a href="contact_store.php?type=3&desc='+item.Description+'&product_id='+item.PartNo+'&year='+sel_year+'&model='+sel_model+'&assembly='+sel_assembly+' " class="contactstore" rel="facebox">Contact Store</a></td>';}
var item_desc;item_desc_full=item.Description;var item_desc_len;item_desc_len=item_desc_full.length;if(item_desc_len>10)
{item_desc='<span title="" onMouseover="ddrivetip(\''+item_desc_full+'\',\'\')"; onMouseout="hideddrivetip()">'+item_desc_full.substring(0,10)+'..</span>';}
else
{item_desc=item_desc_full;}
$('<tr id="part_'+item.PartID+'" class="partrow"></tr>').append('<td class="refCol"><input  id="chk_'+item.PartID+'" type="hidden"></input>'+item.RefNo+'</td><td class="text descCol">'+item_desc+'</td>'+PartNoCell+'<td class="numberCol">'+item.Quantity+'</td><td><input name="qty_'+item.PartID+'" id="qty_'+item.PartID+'" type="text" class="qtyTextbox"  value="'+item.Quantity+'"/></td><td>'+itemPrice+'</td>').append(clm).attr('data-partid',item.PartID).attr('data-partno',itemPartID).attr('data-quantity',item.Quantity).attr('data-price',itemPrice).attr('data-refno',item.RefNo).attr('data-sspartno',item.SsPartNo).attr('data-descrp',item.Description).appendTo('#PartsList tbody');})
$("a.contactstore[rel*=facebox]").facebox({loadingImage:"images/loading.gif",closeImage:"images/closelabel.png"});$('#PartsList tr:odd').addClass('odd');$('#PartsListContainer').fadeIn();});}
function logStatus(statusText){$('textarea#statuslog').val($('textarea#statuslog').val()+'\n'+statusText);}
function clearLog(){$('textarea#statuslog').val('');}
function getModelImage(modelId){$.getJSON('http://'+_domain+'/Model/Image/'+modelId+'/'+DealerID+'?callback=?',function(data){clearLog();logStatus('Image Received');$('div#imageWrap img').remove();if(data.length>0){$.each(data,function(i,item){var modelImage=new Image();modelImage.src='http://'+_domain+'/Image/getImage/'+item.Key+'/type/'+item.Value;$('<img class="modelImage"></img>').attr('src',modelImage.src).css('width','300px').appendTo($('div#imageWrap')).hide().load(function(){$(this).fadeIn();});});}
else{logStatus('No Image');}});}
function getAssemblyImage(assemblyId){$.getJSON('http://'+_domain+'/Assembly/Image/'+assemblyId+'/'+DealerID+'?callback=?',function(data){$('#status').html('Image Received');if(document.getElementById('imageCanvas')){gCanvas=document.getElementById('imageCanvas');gCanvas.width=gCanvas.width;}
_offsetX,_offsetY=0;gImage.onload=function(){$('#status').html('Image Loaded');paint();}
gImage.src='http://'+_domain+'/Image/getImage/'+data.Key+'/type/'+data.Value;});}
$('input.contactstore').live('click',function(){var urlpart=$(this).attr("id").split("_");$(location).attr('href',"contactus.php?product_id="+urlpart[1]+"&desc="+urlpart[2]+"&part=honda");});
